### PR TITLE
Incorporate feedback from validator into examples

### PR DESCRIPTION
**Pull request by FelixHenninger**
Hi Melissa, hej everyone,

with the [validator](https://github.com/psych-ds/validator-prototype) slowly taking shape, I've been testing it on the example datasets, and fixing the issues that the validator has found already. There are a couple of open issues still, notably the object-orientation dataset is still `csv`-based and is missing metadata. But maybe that's for the codebook builder folks? 😜

Ok, so much for now. I hope this helps, please let me know what you think -- all the best, and would love to chat about the validation sometime!

-Felix

### CODE REVIEW

**Comment by mekline** [comment]
This is excellent news, Felix! Thank you so much for working on this, and
it's great news that the example datasets are check-able with the
validator.

I've been struggling to find the time on my own to get the R validator
kicked off, and it would maybe help to have a general developer call, I
think. Would that work for you sometime in the next week or two?

- Melissa

**Comment by FelixHenninger** [comment]
Hi Melissa, thanks for your super-kind response, that sounds awesome!

> I've been struggling to find the time on my own to get the R validator kicked off, and it would maybe help to have a general developer call

Oh yes, I would love that! I'm not 100% sure what you're referring to w/r/t the R validator, I'm guessing you might want to know (just in case you don't already) that the current [validator prototype](https://github.com/psych-ds/validator-prototype) also runs both in the browser and also as an `R` package?
(I couldn't agree more with the points you made at SIPS around the need for interoperability, so we got the same code to work cross-platform. As for the package, we haven't put together an alpha release yet, so the installation instructions in the `readme` won't work -- please let me know if you'd like me to send you a prototype package bundle, I'd be glad to put one together).


> Would that work for you sometime in the next week or two?

Absolutely! I'm available for most of next week from mid-morning your time except for Friday; the week after I'm travelling, but I'd try to make a call work. It would also be great to have @axrhart around, who has contributed a lot esp. around the overall design and structure, and whose ideas stand to improve the code dramatically (I've promised him to write an update email for the mailing list for weeks now, but there's always been one last thing I've wanted to change first). I've also been in contact with Ruben Arslan and Erin Buchanan, who right now is busy with the PsySciAcc website, but (if I understood correctly) would like to work on metadata after.

Ok, so much for now -- I'd genuinely love to pick back up where we left at SIPS, and I'm looking forward to chatting with you sometime soon. All the best,

-Felix

**Comment by mekline** [comment]
Oh fantastic! I didn't realize that the R package had been folded into your
work, which is great news, as I was worried about these efforts getting
disconnected. I'll circulate a poll to try & find a time that works for
those folks, and then put out the call to the psych-ds listserv to make
sure we're not missing others who want to be involved.

**Comment by FelixHenninger** [comment]
That sounds awesome, thanks so much!

**Comment by FelixHenninger** [comment]
(btw., would you like me to merge/rebase this PR? I didn't want to just commit -- if there's anything I should check or could improve, I'd be happy to do so! No hurry though -- if you're there, have a great MetaScience!)

**Comment by mekline** [comment]
@bleonar5 Working on catching up on some (in some cases very) old PRs.  This one has improvements to example dataset metadata many of which which are probably useful to make now.  Can you review/accept the ones that do more closely match current spec?

**Review by bleonar5 — APPROVED** [review]

**Pull request merged**
